/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {    
      colors:{
      'main':"#242424",
      'mainA':"#FFF4CF",
      // 'mainB':"#",
      // 'mainC':"#",
      // 'mainD':"#",
      'back':"#040D12",
      'backA':"#FFAD84",
      'backB':"#750550",
      'backC':"#980F5A",
      // 'backD':"#",
      'card':"#031E1E",
      'cardA':"#FFE382",
      // 'cardB':"#",
      // 'cardC':"#",
      // 'cardD':"#",
      'cardAlt':"#184444",
      'cardAltA':"#FFECA8",
      // 'cardAltB':"#184444",
      // 'cardAltC':"#",
      // 'cardAltD':"#",
      'text':"#93B1A6",
      'textA':"#000000",
      // 'textB':"#",
      // 'textC':"#",
      // 'textD':"#",
      'textAlt':"#040D12",
      'textAltA':"#000000",
      // 'textAltB':"#",
      // 'textAltC':"#",
      // 'textAltD':"#",
      // 'border':"#",
      // 'borderA':"#",
      // 'borderB':"#",
      // 'borderC':"#",
      // 'borderD':"#",
      // 'close':"#",
      'closeA':"#FFAD84",
      // 'closeB':"#",
      // 'closeC':"#",
      // 'closeD':"#",
      // '':"#",
      // '':"#",
      // '':"#",
      // '':"#",
      // '':"#",
      // '':"#",          
      // '':"#",
      // '':"#",
      // '':"#",
      // '':"#",
      // '':"#"
    },},
  },
  plugins: [],
}

